### ISSUE TITLE
Replace awesome badge

### ISSUE THREAD

**Issue by piyushchauhan** [NJACKWinterOfCode/awesome-drones#3]
Replace the current badge with this  one ```[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)```

**Comment by shreyateeza** [comment]
I would like to work on this issue @piyushchauhan

**Comment by shreyateeza** [comment]
@piyushchauhan This badge is already there in the README. Do you mean any other one?

**Comment by piyushchauhan** [comment]
@shreyateeza Actually the badge which is there doesn't follows the guidelines for Awesome lists hence the need for replacement

**Comment by SubhradeepSS** [comment]
Badge replaced in PR #9

**Comment by piyushchauhan** [comment]
Closed by #9
